// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/platform.proto

package go_micro_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{0}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{1}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

type ListEventsRequest struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListEventsRequest) Reset()         { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsRequest) ProtoMessage()    {}
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{2}
}

func (m *ListEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsRequest.Unmarshal(m, b)
}
func (m *ListEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsRequest.Merge(m, src)
}
func (m *ListEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsRequest.Size(m)
}
func (m *ListEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsRequest proto.InternalMessageInfo

func (m *ListEventsRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type ListEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{3}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resource             *Resource         `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Resource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1f44f0a1bd49131, []int{5}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEventRequest)(nil), "go.micro.platform.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "go.micro.platform.CreateEventResponse")
	proto.RegisterType((*ListEventsRequest)(nil), "go.micro.platform.ListEventsRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "go.micro.platform.ListEventsResponse")
	proto.RegisterType((*Event)(nil), "go.micro.platform.Event")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.platform.Event.MetadataEntry")
	proto.RegisterType((*Resource)(nil), "go.micro.platform.Resource")
}

func init() { proto.RegisterFile("proto/platform.proto", fileDescriptor_b1f44f0a1bd49131) }

var fileDescriptor_b1f44f0a1bd49131 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0x52, 0x20, 0x65, 0xc8, 0x9b, 0xc8, 0x88, 0x49, 0x83, 0x1e, 0x48, 0x23, 0x84,
	0xd3, 0x6a, 0xf0, 0xa0, 0xd1, 0x9b, 0x8a, 0x27, 0x4c, 0xcc, 0x5e, 0x4d, 0x4c, 0x56, 0x1c, 0x0d,
	0x91, 0x76, 0xeb, 0xee, 0x42, 0xc2, 0x27, 0xf4, 0x03, 0xf9, 0x05, 0x0c, 0xdb, 0x2d, 0x7f, 0x42,
	0x95, 0x78, 0x9b, 0x99, 0x3e, 0xf3, 0x9b, 0xa7, 0xbb, 0xb3, 0xd0, 0x4c, 0x95, 0x34, 0xf2, 0x24,
	0x9d, 0x08, 0xf3, 0x2a, 0x55, 0xcc, 0x6c, 0x8a, 0x8d, 0x37, 0xc9, 0xe2, 0xf1, 0x48, 0x49, 0x96,
	0x7f, 0x88, 0x6e, 0x01, 0x6f, 0x14, 0x09, 0x43, 0x83, 0x19, 0x25, 0x86, 0xd3, 0xc7, 0x94, 0xb4,
	0x41, 0x06, 0x15, 0x5a, 0xe4, 0xa1, 0xd7, 0xf6, 0x7a, 0xf5, 0x7e, 0xc8, 0xb6, 0x1a, 0x59, 0xa6,
	0xcf, 0x64, 0xd1, 0x01, 0xec, 0x6f, 0x50, 0x74, 0x2a, 0x13, 0x4d, 0xd1, 0x10, 0x1a, 0xc3, 0xb1,
	0x36, 0xb6, 0xa8, 0x73, 0xf6, 0x39, 0x04, 0x8a, 0xb4, 0x9c, 0xaa, 0x11, 0x39, 0xfc, 0x61, 0x01,
	0x9e, 0x3b, 0x09, 0x5f, 0x8a, 0xa3, 0x3b, 0xc0, 0x75, 0x5a, 0x36, 0x03, 0x4f, 0xa1, 0x6a, 0x3d,
	0xe8, 0xd0, 0x6b, 0xfb, 0xbf, 0x7a, 0x75, 0xba, 0xe8, 0xcb, 0x83, 0x8a, 0xad, 0x20, 0x42, 0xd9,
	0xcc, 0xd3, 0xcc, 0x46, 0x8d, 0xdb, 0x18, 0x8f, 0xa0, 0x66, 0xc6, 0x31, 0x69, 0x23, 0xe2, 0x34,
	0x2c, 0xb5, 0xbd, 0x9e, 0xcf, 0x57, 0x05, 0xbc, 0x86, 0x20, 0x26, 0x23, 0x5e, 0x84, 0x11, 0xa1,
	0x6f, 0xe7, 0x75, 0x7f, 0x9a, 0xc7, 0xee, 0x9d, 0x70, 0x90, 0x18, 0x35, 0xe7, 0xcb, 0xbe, 0x8d,
	0x03, 0x28, 0xff, 0xe1, 0x00, 0x5a, 0x57, 0xf0, 0x7f, 0x83, 0x89, 0x7b, 0xe0, 0xbf, 0xd3, 0xdc,
	0xd9, 0x5f, 0x84, 0xd8, 0x84, 0xca, 0x4c, 0x4c, 0xa6, 0x64, 0x9d, 0xd7, 0x78, 0x96, 0x5c, 0x96,
	0x2e, 0xbc, 0xa8, 0x0f, 0x41, 0x8e, 0x2c, 0xfc, 0x6f, 0x84, 0x72, 0x22, 0xe2, 0xbc, 0xd1, 0xc6,
	0xfd, 0x4f, 0x0f, 0x82, 0x07, 0x67, 0x08, 0x9f, 0xa0, 0xbe, 0x76, 0xc7, 0xd8, 0x29, 0xf0, 0xbc,
	0xbd, 0x49, 0xad, 0xee, 0x2e, 0x99, 0x5b, 0x95, 0x7f, 0xf8, 0x08, 0xb0, 0xba, 0x5e, 0x3c, 0x2e,
	0xe8, 0xdb, 0xda, 0xa5, 0x56, 0x67, 0x87, 0x2a, 0x87, 0x3f, 0x57, 0xed, 0x03, 0x38, 0xfb, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0xbb, 0xd3, 0xe7, 0x18, 0x03, 0x00, 0x00,
}
