// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/platform/service/proto/platform.proto

package go_micro_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Platform service

type PlatformService interface {
}

type platformService struct {
	c    client.Client
	name string
}

func NewPlatformService(name string, c client.Client) PlatformService {
	return &platformService{
		c:    c,
		name: name,
	}
}

// Server API for Platform service

type PlatformHandler interface {
}

func RegisterPlatformHandler(s server.Server, hdlr PlatformHandler, opts ...server.HandlerOption) error {
	type platform interface {
	}
	type Platform struct {
		platform
	}
	h := &platformHandler{hdlr}
	return s.Handle(s.NewHandler(&Platform{h}, opts...))
}

type platformHandler struct {
	PlatformHandler
}
