// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/proto/platform.proto

package go_micro_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Unknown          EventType = 0
	EventType_DepoymentCreated EventType = 1
	EventType_DepoymentDeleted EventType = 2
	EventType_DepoymentUpdated EventType = 3
	EventType_SourceUpdated    EventType = 4
	EventType_BuildStarted     EventType = 5
	EventType_BuildFinished    EventType = 6
)

var EventType_name = map[int32]string{
	0: "Unknown",
	1: "DepoymentCreated",
	2: "DepoymentDeleted",
	3: "DepoymentUpdated",
	4: "SourceUpdated",
	5: "BuildStarted",
	6: "BuildFinished",
}

var EventType_value = map[string]int32{
	"Unknown":          0,
	"DepoymentCreated": 1,
	"DepoymentDeleted": 2,
	"DepoymentUpdated": 3,
	"SourceUpdated":    4,
	"BuildStarted":     5,
	"BuildFinished":    6,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{0}
}

type CreateEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{0}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{1}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

type ListEventsRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsRequest) Reset()         { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsRequest) ProtoMessage()    {}
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{2}
}

func (m *ListEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsRequest.Unmarshal(m, b)
}
func (m *ListEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsRequest.Merge(m, src)
}
func (m *ListEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsRequest.Size(m)
}
func (m *ListEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsRequest proto.InternalMessageInfo

func (m *ListEventsRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ListEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{3}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Type                 EventType         `protobuf:"varint,1,opt,name=type,proto3,enum=go.micro.platform.EventType" json:"type,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Service              *Service          `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unknown
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{5}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{6}
}

func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(m, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

type ReadServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadServiceRequest) Reset()         { *m = ReadServiceRequest{} }
func (m *ReadServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadServiceRequest) ProtoMessage()    {}
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{7}
}

func (m *ReadServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceRequest.Unmarshal(m, b)
}
func (m *ReadServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceRequest.Marshal(b, m, deterministic)
}
func (m *ReadServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceRequest.Merge(m, src)
}
func (m *ReadServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadServiceRequest.Size(m)
}
func (m *ReadServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceRequest proto.InternalMessageInfo

func (m *ReadServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ReadServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadServiceResponse) Reset()         { *m = ReadServiceResponse{} }
func (m *ReadServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadServiceResponse) ProtoMessage()    {}
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{8}
}

func (m *ReadServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceResponse.Unmarshal(m, b)
}
func (m *ReadServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceResponse.Marshal(b, m, deterministic)
}
func (m *ReadServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceResponse.Merge(m, src)
}
func (m *ReadServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadServiceResponse.Size(m)
}
func (m *ReadServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceResponse proto.InternalMessageInfo

func (m *ReadServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceRequest) Reset()         { *m = UpdateServiceRequest{} }
func (m *UpdateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceRequest) ProtoMessage()    {}
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{9}
}

func (m *UpdateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceRequest.Unmarshal(m, b)
}
func (m *UpdateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceRequest.Merge(m, src)
}
func (m *UpdateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceRequest.Size(m)
}
func (m *UpdateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceRequest proto.InternalMessageInfo

func (m *UpdateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceResponse) Reset()         { *m = UpdateServiceResponse{} }
func (m *UpdateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceResponse) ProtoMessage()    {}
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{10}
}

func (m *UpdateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceResponse.Unmarshal(m, b)
}
func (m *UpdateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceResponse.Merge(m, src)
}
func (m *UpdateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceResponse.Size(m)
}
func (m *UpdateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceResponse proto.InternalMessageInfo

type DeleteServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceRequest) Reset()         { *m = DeleteServiceRequest{} }
func (m *DeleteServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceRequest) ProtoMessage()    {}
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{11}
}

func (m *DeleteServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceRequest.Unmarshal(m, b)
}
func (m *DeleteServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceRequest.Merge(m, src)
}
func (m *DeleteServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceRequest.Size(m)
}
func (m *DeleteServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceRequest proto.InternalMessageInfo

func (m *DeleteServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeleteServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceResponse) Reset()         { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()    {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{12}
}

func (m *DeleteServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceResponse.Unmarshal(m, b)
}
func (m *DeleteServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceResponse.Merge(m, src)
}
func (m *DeleteServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceResponse.Size(m)
}
func (m *DeleteServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceResponse proto.InternalMessageInfo

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{13}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{14}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_149e17887b265390, []int{15}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.platform.EventType", EventType_name, EventType_value)
	proto.RegisterType((*CreateEventRequest)(nil), "go.micro.platform.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "go.micro.platform.CreateEventResponse")
	proto.RegisterType((*ListEventsRequest)(nil), "go.micro.platform.ListEventsRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "go.micro.platform.ListEventsResponse")
	proto.RegisterType((*Event)(nil), "go.micro.platform.Event")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.platform.Event.MetadataEntry")
	proto.RegisterType((*CreateServiceRequest)(nil), "go.micro.platform.CreateServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "go.micro.platform.CreateServiceResponse")
	proto.RegisterType((*ReadServiceRequest)(nil), "go.micro.platform.ReadServiceRequest")
	proto.RegisterType((*ReadServiceResponse)(nil), "go.micro.platform.ReadServiceResponse")
	proto.RegisterType((*UpdateServiceRequest)(nil), "go.micro.platform.UpdateServiceRequest")
	proto.RegisterType((*UpdateServiceResponse)(nil), "go.micro.platform.UpdateServiceResponse")
	proto.RegisterType((*DeleteServiceRequest)(nil), "go.micro.platform.DeleteServiceRequest")
	proto.RegisterType((*DeleteServiceResponse)(nil), "go.micro.platform.DeleteServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.platform.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.platform.ListServicesResponse")
	proto.RegisterType((*Service)(nil), "go.micro.platform.Service")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.platform.Service.MetadataEntry")
}

func init() { proto.RegisterFile("service/proto/platform.proto", fileDescriptor_149e17887b265390) }

var fileDescriptor_149e17887b265390 = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xe3, 0x38, 0x69, 0x6e, 0x5a, 0xe4, 0xde, 0xa6, 0x60, 0x59, 0x5d, 0x54, 0x16, 0x6d,
	0x23, 0x16, 0x6e, 0x15, 0x10, 0x42, 0xb0, 0x2b, 0x69, 0x25, 0x50, 0x8a, 0x90, 0x43, 0x57, 0x48,
	0x95, 0x4c, 0x3c, 0x80, 0xd5, 0xf8, 0x81, 0x3d, 0x09, 0xca, 0x4f, 0xb0, 0xe0, 0x7b, 0xf8, 0x1e,
	0xbe, 0x03, 0x79, 0x66, 0x9c, 0xda, 0xc9, 0xb8, 0x41, 0x4a, 0x76, 0x99, 0xe3, 0x33, 0xe7, 0x3e,
	0xe6, 0xde, 0xa3, 0xc0, 0x61, 0x4a, 0x92, 0xa9, 0x3f, 0x22, 0x67, 0x71, 0x12, 0xd1, 0xe8, 0x2c,
	0x1e, 0xbb, 0xf4, 0x6b, 0x94, 0x04, 0x36, 0x3b, 0xe2, 0xde, 0xb7, 0xc8, 0x0e, 0xfc, 0x51, 0x12,
	0xd9, 0xf9, 0x07, 0xab, 0x0f, 0xf8, 0x36, 0x21, 0x2e, 0x25, 0x97, 0x53, 0x12, 0x52, 0x87, 0xfc,
	0x98, 0x90, 0x94, 0xa2, 0x0d, 0x1a, 0xc9, 0xce, 0x86, 0x72, 0xa4, 0x74, 0xdb, 0x3d, 0xc3, 0x5e,
	0xba, 0x68, 0x73, 0x3e, 0xa7, 0x59, 0x07, 0xb0, 0x5f, 0x52, 0x49, 0xe3, 0x28, 0x4c, 0x89, 0xf5,
	0x0e, 0xf6, 0x06, 0x7e, 0x4a, 0x19, 0x98, 0xe6, 0xda, 0x2f, 0xa0, 0x29, 0x92, 0x14, 0xea, 0xa6,
	0x44, 0x7d, 0xc8, 0x19, 0x4e, 0x4e, 0xb5, 0xae, 0x00, 0x8b, 0x52, 0x3c, 0x00, 0x9e, 0x43, 0x83,
	0x25, 0x90, 0x1a, 0xca, 0x91, 0xfa, 0x60, 0xa2, 0x82, 0x67, 0xfd, 0xaa, 0x81, 0xc6, 0x10, 0x3c,
	0x87, 0x3a, 0x9d, 0xc5, 0x3c, 0x89, 0x47, 0xbd, 0xc3, 0xaa, 0x9b, 0x9f, 0x66, 0x31, 0x71, 0x18,
	0x13, 0x0f, 0xa1, 0x45, 0xfd, 0x80, 0xa4, 0xd4, 0x0d, 0x62, 0xa3, 0x76, 0xa4, 0x74, 0x55, 0xe7,
	0x1e, 0xc0, 0x0b, 0xd8, 0x0e, 0x08, 0x75, 0x3d, 0x97, 0xba, 0x86, 0xca, 0xb2, 0x39, 0xa9, 0xd2,
	0xb4, 0xaf, 0x05, 0xf1, 0x32, 0xa4, 0xc9, 0xcc, 0x99, 0xdf, 0x2b, 0xf6, 0xa6, 0xfe, 0xdf, 0xbd,
	0x31, 0xdf, 0xc0, 0x6e, 0x49, 0x10, 0x75, 0x50, 0xef, 0xc8, 0x8c, 0x55, 0xd6, 0x72, 0xb2, 0x9f,
	0xd8, 0x01, 0x6d, 0xea, 0x8e, 0x27, 0x84, 0xa5, 0xdd, 0x72, 0xf8, 0xe1, 0x75, 0xed, 0x95, 0x62,
	0x0d, 0xa0, 0xc3, 0x9f, 0x2e, 0x97, 0x5d, 0xeb, 0x99, 0x9e, 0xc0, 0xc1, 0x82, 0x9a, 0x18, 0x85,
	0xf7, 0x80, 0x0e, 0x71, 0xbd, 0x8d, 0x04, 0xb9, 0x86, 0xfd, 0x92, 0x96, 0x18, 0x86, 0x97, 0xb0,
	0x2d, 0x18, 0xf9, 0x38, 0x3c, 0xa4, 0x36, 0xe7, 0x66, 0x1d, 0xb8, 0x89, 0xbd, 0x0d, 0x76, 0x60,
	0x41, 0x4d, 0x74, 0x60, 0x00, 0x9d, 0x3e, 0x19, 0x93, 0xcd, 0x85, 0x59, 0x50, 0x13, 0x61, 0x0e,
	0x60, 0x3f, 0x5b, 0x14, 0x01, 0xe7, 0x5b, 0x67, 0x7d, 0x80, 0x4e, 0x19, 0x5e, 0xb3, 0x69, 0x7f,
	0x15, 0x68, 0x0a, 0x14, 0x11, 0xea, 0xa1, 0x1b, 0x10, 0x31, 0x6f, 0xec, 0x37, 0x1a, 0xd0, 0x9c,
	0x92, 0x24, 0xf5, 0xa3, 0x50, 0x8c, 0x5c, 0x7e, 0xc4, 0xc7, 0xd0, 0x48, 0xa3, 0x49, 0x32, 0x22,
	0x86, 0xca, 0x3e, 0x88, 0x53, 0xa6, 0xc2, 0xf6, 0xb1, 0xce, 0x55, 0xd8, 0xc6, 0xf5, 0x0b, 0x3b,
	0xa5, 0xb1, 0xec, 0xba, 0xd5, 0xd9, 0x55, 0x6d, 0xd5, 0x5a, 0xfb, 0xf1, 0xec, 0xb7, 0x02, 0xad,
	0xb9, 0x11, 0x60, 0x1b, 0x9a, 0x37, 0xe1, 0x5d, 0x18, 0xfd, 0x0c, 0xf5, 0x2d, 0xec, 0x80, 0xde,
	0x27, 0x71, 0x34, 0x0b, 0x48, 0x48, 0xf9, 0xd4, 0x7b, 0xba, 0x52, 0x42, 0xf9, 0x13, 0x79, 0x7a,
	0xad, 0x84, 0xf2, 0xf9, 0xf0, 0x74, 0x15, 0xf7, 0x60, 0x77, 0xc8, 0xaa, 0xcf, 0xa1, 0x3a, 0xea,
	0xb0, 0x73, 0x31, 0xf1, 0xc7, 0xde, 0x90, 0xba, 0x49, 0x86, 0x68, 0x19, 0x89, 0x21, 0x57, 0x7e,
	0xe8, 0xa7, 0xdf, 0x89, 0xa7, 0x37, 0x7a, 0x7f, 0x34, 0xd8, 0xfe, 0x28, 0xca, 0xc7, 0x5b, 0x68,
	0x17, 0xcc, 0x17, 0x8f, 0x25, 0x1d, 0x5a, 0xb6, 0x78, 0xf3, 0x64, 0x15, 0x4d, 0xcc, 0xd3, 0x16,
	0x7e, 0x06, 0xb8, 0xb7, 0x5e, 0x7c, 0x2a, 0xb9, 0xb7, 0x64, 0xf2, 0xe6, 0xf1, 0x0a, 0xd6, 0x5c,
	0xdc, 0x83, 0xdd, 0x92, 0x61, 0xe0, 0x69, 0x65, 0x5e, 0xe5, 0xbd, 0x31, 0xbb, 0xab, 0x89, 0xf3,
	0x28, 0xb7, 0xd0, 0x2e, 0x38, 0x86, 0xb4, 0x45, 0xcb, 0xee, 0x24, 0x6d, 0x91, 0xc4, 0x78, 0x78,
	0x15, 0xa5, 0xa5, 0x97, 0x56, 0x21, 0x33, 0x19, 0x69, 0x15, 0x72, 0xff, 0x60, 0x51, 0x4a, 0x3b,
	0x2f, 0x8d, 0x22, 0xf3, 0x18, 0x69, 0x14, 0xb9, 0x7d, 0x6c, 0xa1, 0x0b, 0x3b, 0x45, 0xa7, 0xc0,
	0x93, 0x8a, 0xa7, 0x5c, 0x70, 0x18, 0xf3, 0x74, 0x25, 0x2f, 0x0f, 0xf1, 0xa5, 0xc1, 0xfe, 0x8e,
	0x3c, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xed, 0xbf, 0x5e, 0xae, 0x08, 0x00, 0x00,
}
